spring:
  datasource:
    url: jdbc:h2:mem:returndb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: true
#    show-sql: true
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

server:
  port: 8000

#logging:
#  level:
#    org:
#      hibernate:
#        sql: debug
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
